### ISSUE TITLE
Support `latin1` strings with `ascii` `target_url's`

### ISSUE THREAD

**Issue by twolfson** [underdogio/python-resolve-link#2]
We have encountered a regression when an `ascii` `target_url` attempts to use a `latin1` string in its target URL. We should support proper coercion:

```python
>>> resolve_link.resolve_link('twolfson', 'http://github.com/')
'http://github.com/twolfson'
>>> resolve_link.resolve_link(u'twolfsõn', 'http://github.com/')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "resolve_link/__init__.py", line 26, in resolve_link
    tmp_src_url = '//{src_url}'.format(src_url=src_url)
UnicodeEncodeError: 'ascii' codec can't encode character u'\xf5' in position 6: ordinal not in range(128)
```

**Comment by twolfson** [comment]
This has been fixed in #3 and released as `1.1.0`.
